FROM quay.io/fedora/fedora:32-s390x

USER root

ENV GOPATH=/go

RUN mkdir /workspace && chmod 777 workspace

RUN curl -sL -o /tmp/oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux-s390x/oc.tar.gz && \
tar -C /tmp -xf /tmp/oc.tar.gz --no-same-owner && \
mv /tmp/oc /usr/local/bin && \
chmod +x /usr/local/bin/oc && \
rm /tmp/*

RUN dnf -y install jq container-selinux --enablerepo updates-testing

RUN cd /workspace && git clone https://github.com/utherp0/workshop4

WORKDIR /workspace

EXPOSE 8080

USER 1001

ENV HOME=/workspace

ENTRYPOINT ["/go/bin/gotty"]
CMD ["-w","bash"]
