kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: nodejs
  SourceLocation: ./
  SourceType: local
  Ports:
  - 8080/TCP
  Application: app
  Project: sandbox-97
  Name: node-app-rest-97
  Url:
  - Name: node-app-rest
    Port: 8080
