apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-5
spec:
  tasks:
  - name: task-5
    taskRef:
      name: task-5
  - name: task-6
    taskref:
      name: task-6
    runAfter: 
    - task-5
