apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipelinetest
spec:
  tasks:
#  - name: login
#    taskRef:
#      name: tasklogin
  - name: clone
    taskRef:
      name: taskclone
#    runAfter:
#      - login
  - name: wait
    taskref:
      name: taskwatch
    runAfter:
      - clone
