apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: taskwatch
spec:
  steps:
    - name: watchls
      image: quay.io/ilawson/oconline
      command:
        - ls
      args:
        - "-alR"
    - name: watchwait
      image: quay.io/ilawson/oconline
      command:
        - /bin/bash
      args:
        - "workshop4/attendee/tekton/watch.sh"