apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-2
spec:
  steps:
    - name: what-directory
      image: quay.io/openshift/origin-cli:latest
      command: ["pwd"]
    - name: describe-command
      image: quay.io/openshift/origin-cli:latest
      command: ["echo"]
      args: [
        "------------------------------------------------------------\n",
        " - Openshift OC command line example \n",
        "------------------------------------------------------------\n",
      ]
    - name: oc-version
      image: quay.io/openshift/origin-cli:latest
      command: ["oc"]
      args: ["version"]