apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-5
spec:
  steps:
    - name: create-a-file-in-workspace
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash"]
      args: ['-c', 'echo "This is a file in the workspace" > /workspace/message && ls /workspace/message']
    - name: view-workspace-content
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash"]
      args: ['-c', 'ls /workspace && cat /workspace/message']
    - name: create-a-file-in-volume
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash"]
      args: ['-c', 'echo "This is a file in the volume" > /var/run/message && ls /var/run/message']  
      volumeMounts:
        - mountPath: /var/run
          name: pipeline-cache          
    - name: view-volume-content
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash"]
      args: ['-c', 'ls /var/run && cat /var/run/message']
      volumeMounts:
        - mountPath: /var/run
          name: pipeline-cache
  volumes:
  - name: pipeline-cache
    persistentVolumeClaim:
      claimName: tekton-task-cache-pvc      