id: "essentials"
name: "OpenShift Essentials"

content:
  url: http://labs:8080/labs

vars:
  OPENSHIFT_CONSOLE_URL: "https://console-openshift-console.mycluster.com"

modules:
  activate:
  - applicationbasics
  - deployments
  - applicationdeploymentstrategies
  - sdn
  - rbac
  - pvs
  - healthprobes
  - metrics
  