id: "intro"
name: "Introduction and Setup"

content:
  url: http://labs:8080/labs

vars:
  OPENSHIFT_CONSOLE_URL: "https://console-openshift-console.mycluster.com"

modules:
  activate:
  - intro
  - prereq
  