---
# file: main.yml

# Deploy the Openshift Serverless Opeartor

- name: Deploy Openshift Serverless Operator
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    src: "{{ role_path }}/files/serverlessoperator.yaml"

# Create the Knative serving namespace and KnativeServing CRD
- name: Create Knative serving namespace
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    src: "{{ role_path }}/files/knativenamespace.yaml"

- name: pause
  pause: 
    minutes: "2"

# Create the Knative serving namespace and KnativeServing CRD
- name: Create Knative serving CRD
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    src: "{{ role_path }}/files/serving.yaml"
    wait: yes


# Wait for Knative serving to be ready before continuing
- name: Is Knative servering deployed?
  shell: oc get knativeserving.operator.knative.dev/knative-serving -n knative-serving -o jsonpath="{.status.conditions[3].status}"
  register: knative
  until: knative.stdout.find("True") != -1
  retries: 400
  delay: 5
