apiVersion: eventing.knative.dev/v1alpha1
kind: KnativeEventingKafka
metadata:
  name: knative-eventing-kafka
  namespace: knative-eventing
spec:
  bootstrapServers: 'kafka-cluster-kafka-bootstrap:9092'
  setAsDefaultChannelProvisioner: false